#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
#
# Text labels and messages used in LOADSAVE.C
#
# (These MUST match "text message" enumeration on the top of LOADSAVE.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?

# System
{100}{}{CARREGAR O JOGO}        # Titles
{101}{}{ESCOLHA UM SLOT}
{102}{}{SALVAR O JOGO}
{103}{}{ESCOLHA UM SLOT}
{104}{}{FEITO}
{105}{}{CANCELAR}
{106}{}{Erro ao carregar a lista de jogos salvos!}  # Line 1
{107}{}{Diretório dos jogos salvos:}                # Line 2
{108}{}{Não existe ou esta corrompido.}             # Line 3
{109}{}{SALVAR O JOGO}
{110}{}{CARREGAR O JOGO}
{111}{}{- VAZIO -}
{112}{}{- ARQUIVO CORROMPIDO -}
{113}{}{- VERSÃO ANTIGA -}
{114}{}{Vazio.}
{115}{}{Erro!}
{116}{}{Versão antiga.}
# Months
{117}{}{JAN}
{118}{}{FEV}
{119}{}{MAR}
{120}{}{ABR}
{121}{}{MAI}
{122}{}{JUN}
{123}{}{JUL}
{124}{}{AGO}
{125}{}{SET}
{126}{}{OUT}
{127}{}{NOV}
{128}{}{DEZ}
{129}{}{Nível}
{130}{}{DESCRIÇÃO}
{131}{}{Ja existe um jogo salvo, sobrescrever?}
{132}{}{Erro ao salvar o jogo!}             # Line 1
{133}{}{Incapaz de salvar o jogo.}          # Line 2
{134}{}{Erro ao carregar o jogo!}           # Line 1
{135}{}{Incapaz de carregar o jogo.}        # Line 2
{136}{}{O arquivo do jogo salvo esta em uma versão mais antiga.}
{137}{}{Mapa}

{140}{}{Jogo Salvo.}
{141}{}{Jogo Carregado.}
#
# Demo versions only
#
{200}{}{Lamento, você não pode salvar ou carregar}  # 1
{201}{}{na versão demo.}                            # 2
